<File>
  <BAQ_details>
    <Details>
      <Company>HA</Company>
      <QueryID>fun</QueryID>
      <AuthorID>domurto</AuthorID>
      <Description>fun</Description>
      <DisplayPhrase></DisplayPhrase>
      <IsGlobal>False</IsGlobal>
      <IsShared>True</IsShared>
      <Updatable>False</Updatable>
      <SysRevID>System.Byte[]</SysRevID>
      <SysRowID>31627e08-e3f4-4913-80c3-356acd592598</SysRowID>
    </Details>
  </BAQ_details>
</File>